### PR TITLE
scala 2.12.3 and sbt 0.13.16

### PR DESCRIPTION
**Pull request by bpholt**

### CODE REVIEW

**Comment by bpholt** [comment]
~~This isn't ready yet because [sbt hasn't published 0.13.16 to bintray](https://github.com/sbt/sbt/issues/3384).~~

See [comment below](https://github.com/Dwolla/jenkins-agent-docker-sbt/pull/4#issuecomment-318696501).

**Comment by NeQuissimus** [comment]
If you change the Dockerfile's `apk add --update git` to `apk add --no-cache git`, you won't need the `rm -rf` or the cache directory at the end, btw.

**Comment by bpholt** [comment]
@NeQuissimus thanks for the tip!

**Comment by bpholt** [comment]
Since `0.13.16` is called for by the fake sbt project, the Docker image will initially download sbt 0.13.15 and then download 0.13.16 when it runs `sbt`. Both versions will end up in the final build, along with all the Scala versions mentioned in the fake project. I think that's good enough for now.

**Review by jareddellitt — APPROVED** [review]

**Pull request merged**
